macOS Wine (#8)

diff --git a/scriptbox/config/macos.yml b/scriptbox/config/macos.yml
--- a/scriptbox/config/macos.yml
+++ b/scriptbox/config/macos.yml
@@ -75,6 +75,9 @@ macos:
         packages:
           - cask: wine-stable
             script: macos_wine_fix
+          - brew: wintricks
+            script: macos_winetricks_wsh57
+          - script: wine_coreutils
         powershell:
           packages:
             - brew: powershell
@@ -138,6 +141,40 @@ scripts:
     cmd: |
       echo 'export JAVA_HOME=$(/usr/libexec/java_home -v 17)' >> ~/.bashrc
       echo 'export JAVA_HOME=$(/usr/libexec/java_home -v 17)' >> ~/.zshrc
+  macos_winetricks_wsh57:
+    type: bash
+    cmd: |
+      winetricks wsh57
+
+      WINE_APP_STUBS="/Applications/Wine Stable.app/Contents/Resources/wine/lib/wine/x86_64-windows"
+      SYS32="$HOME/.wine/drive_c/windows/system32"
+      SYSWOW64="$HOME/.wine/drive_c/windows/syswow64"
+
+      cp "${SYSWOW64}/cscript.exe" "${SYS32}/cscript.exe"
+      cp "${SYSWOW64}/wscript.exe" "${SYS32}/wscript.exe"
+  wine_coreutils:
+    type: bash
+    cmd: |
+        pushd $HOME/Downloads
+
+        # Download coreutils
+        curl -LO https://github.com/microsoft/coreutils/releases/download/v2026.6.16/coreutils-2026.6.16-x64.exe
+        
+        # Verify checksum
+        ACTUAL_SHA=$(shasum -a 256 coreutils-2026.6.16-x64.exe | cut -f1 -d' ')
+        EXPECTED_SHA="f862b1aa433310420ae20f9b1384f3f974a26ba98ae37ac548061116a3ef6c62"
+        
+        if [ "$ACTUAL_SHA" != "$EXPECTED_SHA" ]; then
+          echo "ERROR: CHECKSUM MISMATCH - DO NOT USE THIS FILE" >&2
+          exit 1
+        fi
+        echo "CHECKSUM OK"
+        
+        # install coreutils 
+        wine coreutils-2026.6.16-x64.exe /VERYSILENT /SUPPRESSMSGBOXES /NORESTART /SP-
+        
+        popd
+
 
     
 
